# Generated by Django 3.0.8 on 2020-12-02 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_profile',
        ),
    ]
