# Generated by Django 3.0.8 on 2020-08-01 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_in', models.CharField(max_length=200)),
                ('made_by', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('BOTH', 'Both')], default='BOTH', max_length=10)),
                ('form', models.CharField(max_length=100)),
                ('pack_of', models.CharField(max_length=100)),
                ('dosage', models.TextField()),
                ('usage', models.TextField()),
                ('cases', models.TextField()),
                ('storing', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nesting_level', models.IntegerField()),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_category', to='iteminfo.Category')),
            ],
        ),
    ]
