# Generated by Django 3.0.8 on 2020-09-26 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iteminfo', '0002_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='nesting_level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
