# Generated by Django 3.0.8 on 2020-09-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteminfo', '0003_auto_20200926_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standarddescription',
            name='cases',
        ),
        migrations.RemoveField(
            model_name='standarddescription',
            name='made_by',
        ),
        migrations.AddField(
            model_name='standarddescription',
            name='features',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='standarddescription',
            name='short_description',
            field=models.TextField(default=''),
        ),
    ]
