# Generated by Django 3.0.8 on 2020-09-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteminfo', '0004_auto_20200926_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarddescription',
            name='gender',
            field=models.CharField(choices=[('MALE', 'آقایان'), ('FEMALE', 'خانمها'), ('BOTH', 'عمومی')], default='BOTH', max_length=10),
        ),
    ]
