# Generated by Django 3.0.8 on 2020-10-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteminfo', '0006_auto_20201027_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='nesting_level',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
