# Generated by Django 3.0.8 on 2020-10-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iteminfo', '0007_subcategory_nesting_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='sub_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iteminfo.SubCategory'),
        ),
    ]
