# Generated by Django 3.0.8 on 2020-12-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteminfo', '0009_auto_20201027_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarddescription',
            name='dosage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='standarddescription',
            name='features',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='standarddescription',
            name='form',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='standarddescription',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'آقایان'), ('FEMALE', 'خانمها'), ('BOTH', 'عمومی')], default='BOTH', max_length=10),
        ),
        migrations.AlterField(
            model_name='standarddescription',
            name='made_in',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standarddescription',
            name='pack_of',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='standarddescription',
            name='short_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='standarddescription',
            name='storing',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='standarddescription',
            name='usage',
            field=models.TextField(blank=True),
        ),
    ]
