# Generated by Django 3.0.8 on 2020-12-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteminfo', '0010_auto_20201202_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nesting_level',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
