# Generated by Django 3.0.8 on 2020-12-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('full_address', models.CharField(max_length=120)),
                ('postal_code', models.IntegerField()),
                ('receiver', models.CharField(max_length=120)),
                ('receiver_phone', models.CharField(max_length=120)),
            ],
        ),
    ]
