# Generated by Django 3.0.8 on 2020-12-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='plaque',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='full_address',
            field=models.TextField(),
        ),
    ]
