# Generated by Django 3.0.8 on 2020-12-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20201212_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='receiver',
        ),
        migrations.AddField(
            model_name='address',
            name='flat',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='receiver_firstname',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='receiver_lastname',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
