# Generated by Django 3.0.8 on 2020-12-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_remove_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='melli_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
